name: CI devtool

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  format:
    name: Format devtool
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        working-directory: src/devtool
        run: cargo fmt --check

  build:
    name: Build and Upload devtool
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --release
        working-directory: src/devtool
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devtool-${{ matrix.os }}-${{ github.sha }}
          path: src/devtool/target/release/hush${{ matrix.os == 'windows-latest' && '.exe' || '' }}

    runs-on: ${{ matrix.os }}